name: dmbs_frontend
description: Database Management System Frontend Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  http: ^1.6.0
  file: ^7.0.1
  file_picker: ^11.0.2
  # State Management
  flutter_riverpod: ^2.6.1
  # HTTP Client (backend entegrasyonu için)
  dio: ^5.7.0
  # Token / ayar kalıcılığı
  shared_preferences: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
